### ISSUE TITLE
Claimed for campaign discrepancy

### ISSUE THREAD

**Issue by tass21fr** [CPChain/chain#38] opened 2019-05-18 15:19 UTC
**Where does the bug occur?**
in the console vs the explorer

**What is your wallet address and your balance?**
0x2c1dDB925c5b574F39B0641e07dEA16488A1A9f7
34k tokens of balance

**Describe the bug**
In the console I get the message claimed for campaign for block 413 750.
![image](https://user-images.githubusercontent.com/50399702/57971500-597a9200-798f-11e9-9a57-3facca202b7c.png)

In the explorer, adress 0x4c61559aa727380e3fa516b6a7ae397b87ec2384 is the block producer.

**To Reproduce**
My server usually gets the "error in claiming campaign" and I cannot produce blocks. I stoped the server and restarted. I had the bug i describe above. I tried to reproduce the bug by stopping the server and restarting but could not reproduce the bug. I get the "error in claiming campaign message"

**Expected behavior**
I expect an error message in the console if I do not really claim this block

**Screenshots**

** Configuration (please complete the following information):**
 - OS: Ubuntu 19.04
 - cpchain version  0.2.8

**Comment by tass21fr** [comment] 2019-05-19 09:00
Happened again with block 437659 after stopping and restarting cpchain process on the server.

**Comment by alex031029** [comment] 2019-05-22 02:37
Looks like it is also a bug related to #12 . As you stated, this bug is hard to reproduce. Since we have published a new version, I am about to close this one. And feel free to open a new one if you encounter similar problem again.

**Closed by alex031029** 2019-05-22 02:37 UTC
