### ISSUE TITLE
No Trx or Blocks in v 0.2.6 + Error in claiming campaign

### ISSUE THREAD

**Issue by equilibrium20** [CPChain/chain#22] opened 2019-05-11 12:37 UTC
After upgrading to v 0.2.6, it syncs and imports new chain segments. However, no more transactions or block sealing happens.
Also, getting the following Error in claiming every time

WARN[05-11|11:35:39.055] Error in claiming campaign                    error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"
![gasError](https://user-images.githubusercontent.com/50518870/57569775-f81f5580-73c7-11e9-990b-7b0980b41de6.gif)

**Comment by alex031029** [comment] 2019-05-11 12:49
This bug is rather tricky. We know we have not fixed it yet. So I leave https://github.com/CPChain/chain/issues/12 open.

**Comment by hvredevoort** [comment] 2019-05-12 08:30
Running into the same problem with this version. Started many times, but this did not solve it.

**Comment by brammb** [comment] 2019-05-12 08:59
Also running into the same problem with 2.6

**Comment by NielDS** [comment] 2019-05-13 13:27
Same bug in 2.7 seen

**Comment by alex031029** [comment] 2019-05-14 07:55
@NielDS Did you encountered same issue in 0.2.7? The bug with this error message is supposed to be fixed in 0.2.7. In case you find it again please post here or raise a new issue.

**Comment by alex031029** [comment] 2019-05-14 13:03
This problem is another manifestation of #12 , caused by same code. We close it and merge this issue to #12 .

**Closed by alex031029** 2019-05-14 13:03 UTC
