### ISSUE TITLE
Tx receipt status Fail why!? 

### ISSUE THREAD

**Issue by HKet** [CPChain/chain#55] opened 2019-05-26 09:54 UTC
**Where does the bug occur?**
explorer block details view

**What is your wallet address and your balance?**
0x28E8FbACC91e01D5F111017C0fC969334c7FDE87
355k

**Describe the bug**
In the details of a particular block the TX status is Fail, it is unclear why this block gets TxStatus Fail.
There is no error, no warning or anything else that indicates a specific issue in the RNodelogging concerning this block and around the time of occurrence.
Logging:
INFO[05-26|09:40:48.348] Synchronization Started                       Line="syncer/syncer.go:430" local height=492735 peer=369699f91013336e peer.Head=0xfa3fd3ecb4d7ba2c318c8b652b178a8e36430dedc9ff8aa355290a1ab66c71cf peer.height=492736
INFO[05-26|09:40:48.353] Synchronization Started                       Line="syncer/syncer.go:430" local height=492735 peer=1dd1d0d779f3ed0d peer.Head=0xfa3fd3ecb4d7ba2c318c8b652b178a8e36430dedc9ff8aa355290a1ab66c71cf peer.height=492736
INFO[05-26|09:40:48.353] Synchronization Started                       Line="syncer/syncer.go:430" local height=492735 peer=be14fce25a846bd5 peer.Head=0xfa3fd3ecb4d7ba2c318c8b652b178a8e36430dedc9ff8aa355290a1ab66c71cf peer.height=492736
INFO[05-26|09:40:48.356] Synchronization Started                       Line="syncer/syncer.go:430" local height=492735 peer=943f0474c19bb2b5 peer.Head=0xfa3fd3ecb4d7ba2c318c8b652b178a8e36430dedc9ff8aa355290a1ab66c71cf peer.height=492736
INFO[05-26|09:40:48.364] Synchronization Started                       Line="syncer/syncer.go:430" local height=492735 peer=6d0c212e72718e8a peer.Head=0xfa3fd3ecb4d7ba2c318c8b652b178a8e36430dedc9ff8aa355290a1ab66c71cf peer.height=492736
INFO[05-26|09:40:48.389] Synchronization Started                       Line="syncer/syncer.go:430" local height=492735 peer=7993354fb848714f peer.Head=0xfa3fd3ecb4d7ba2c318c8b652b178a8e36430dedc9ff8aa355290a1ab66c71cf peer.height=492736
INFO[05-26|09:40:48.429] Synchronization Started                       Line="syncer/syncer.go:430" local height=492735 peer=5960fac611f48724 peer.Head=0xfa3fd3ecb4d7ba2c318c8b652b178a8e36430dedc9ff8aa355290a1ab66c71cf peer.height=492736
INFO[05-26|09:40:48.435] Synchronization Started                       Line="syncer/syncer.go:430" local height=492735 peer=47d12c0863241f68 peer.Head=0xfa3fd3ecb4d7ba2c318c8b652b178a8e36430dedc9ff8aa355290a1ab66c71cf peer.height=492736
INFO[05-26|09:40:48.438] Synchronization Started                       Line="syncer/syncer.go:430" local height=492735 peer=c934dea6caf76cc3 peer.Head=0xfa3fd3ecb4d7ba2c318c8b652b178a8e36430dedc9ff8aa355290a1ab66c71cf peer.height=492736
INFO[05-26|09:40:48.475] Synchronization Started                       Line="syncer/syncer.go:430" local height=492735 peer=a858243c37af20e1 peer.Head=0xfa3fd3ecb4d7ba2c318c8b652b178a8e36430dedc9ff8aa355290a1ab66c71cf peer.height=492736
INFO[05-26|09:40:48.746] Imported new chain segment                    Line="core/blockchain.go:1577" blocks=1 cache="307.69 kB" elapsed=395.950ms hash=0xfa3fd3ecb4d7ba2c318c8b652b178a8e36430dedc9ff8aa355290a1ab66c71cf mgas=5.632173 mgasps=14.2244362115079 number=492736 txCounterAfterStartup=28160 txs=24
INFO[05-26|09:40:57.944] Synchronization Started                       Line="syncer/syncer.go:430" local height=492736 peer=be14fce25a846bd5 peer.Head=0xf96341bb05b7fb2465167f68ae93c5836e527952004e692200a3000fcb61fa50 peer.height=492737
INFO[05-26|09:40:57.944] Synchronization Started                       Line="syncer/syncer.go:430" local height=492736 peer=369699f91013336e peer.Head=0xf96341bb05b7fb2465167f68ae93c5836e527952004e692200a3000fcb61fa50 peer.height=492737
INFO[05-26|09:40:57.946] Synchronization Started                       Line="syncer/syncer.go:430" local height=492736 peer=943f0474c19bb2b5 peer.Head=0xf96341bb05b7fb2465167f68ae93c5836e527952004e692200a3000fcb61fa50 peer.height=492737
INFO[05-26|09:40:57.948] Synchronization Started                       Line="syncer/syncer.go:430" local height=492736 peer=1dd1d0d779f3ed0d peer.Head=0xf96341bb05b7fb2465167f68ae93c5836e527952004e692200a3000fcb61fa50 peer.height=492737
INFO[05-26|09:40:57.950] Imported new chain segment                    Line="core/blockchain.go:1577" blocks=1 cache="1.71 kB" elapsed=4.467ms hash=0xf96341bb05b7fb2465167f68ae93c5836e527952004e692200a3000fcb61fa50 mgas=0 mgasps=0 number=492737 

**To Reproduce**
I do not know how to reproduce it but it occurred at least 1 time before also
The blocks i found where this issue occurred are:
 492736 and 484964
(see pictures of these blocks below)

In both situations the blocks are 

**Expected behavior**
I expect that my RNode can process all blocks successfully!

**Screenshots**

block 492736
![image 1](https://user-images.githubusercontent.com/24922860/58380158-15e6e000-7fae-11e9-9242-d905e037fdfd.png)

block 489064
![image 2](https://user-images.githubusercontent.com/24922860/58380167-2dbe6400-7fae-11e9-8c93-81756185981b.png)

** Configuration (please complete the following information):**
 - Centos 7
 - cpchain version 0.2.9.

**Additional context**
If your bug can only be reproduced occasionally, please emphasize it.

**Comment by alex031029** [comment] 2019-06-03 12:27
This problem should be fixed in 0.2.11. In case you witness it again, please open a new issue.

Now, let me explain the reason. A failed transaction was caused by an insufficient gas. When a node claimed campaign, it pre-calculated a minimum gas for this claim, and set it as gas limit. But this pre-calculation can be wrong, since some new transactions are added into the chain between the time of pre-calculation and the time of transaction getting onto the chain. 

Now we adjust the algorithm such that the node will pay a slightly higher gas limit. It can largely reduce the chance of failed transaction of claiming campaign happening.

**Closed by alex031029** 2019-06-03 12:27 UTC
